### ISSUE TITLE
Implement basic CLI

### ISSUE THREAD

**Issue by mycognosist** [peachcloud/peach-probe#2]
Since `peach-probe` is intended to be a CLI tool, we need a way to parse arguments and act accordingly.

There are several argument-parsing crates available, including popular options such as [clap](https://crates.io/crates/clap) and [structopt](https://crates.io/crates/structopt). Personally, I'm quite fond of the simplicity of structopt - which essentially only requires the definition and annotation of a struct.

The Rust CLI tutorial has a neat section called [Parsing CLI arguments with StructOpt](https://rust-cli.github.io/book/tutorial/cli-args.html#parsing-cli-arguments-with-structopt). The entire tutorial is very helpful as a guide to building CLI tools with Rust. [`peach-monitor`](https://github.com/peachcloud/peach-monitor/blob/master/src/main.rs) uses structopt and may provide a useful reference.

**Comment by mhfowler** [comment]
Implemented by https://github.com/peachcloud/peach-probe/pull/6
