### ISSUE TITLE
Defining the CLI API

### ISSUE THREAD

**Issue by mycognosist** [peachcloud/peach-probe#3]
Let's use this as a place to discuss and define the API of the `peach-probe` CLI tool.

**Basic Functionality**

My initial thoughts are that it should probe all microservices when called without any arguments, and that it should be possible to probe individual services by passing arguments or flags. For example:

// probe all microservices
`peach-probe` 

// probe only the peach-stats microservice
`peach-probe stats`

// probe the peach-stats, peach-network and peach-oled microservices
`peach-probe stats network oled`

**Verbosity**

A verbosity flag may be useful to offer additional insight into which RPC methods are being probed and what their responses are. Example:

// probe the peach-oled microservice and provide verbose output
`peach-probe oled -v`

**Custom Port Numbers**

Port numbers for microservices should default to those defined in the code (for example, `peach-stats` defaults to 5113). It may be useful to add custom port definition in a future version of `peach-probe`, though I don't think this is super important to begin with. Such functionality might be invoked as follows:

// probe the peach-network microservice on a custom port
`peach-probe network --port 5999`

**Comment by mhfowler** [comment]
going to start working on the peach-stats test first, 
but just noting, not sure what best practice would be for specifying port for each microservice with CLI 

peach-probe network --port 5999 oled --port 5788

as from initial reading I'm not sure how structopt or clap would like having multiple args with the same --port name.
could also have different args for each, like --network-port 5999 and --oled-port 5788 but thats a lot of custom args

alternatively could be a syntax like 

peach-probe network:5999 oled:5788

and if there is no colon, then it uses the default port

**Comment by mycognosist** [comment]
One option would be to follow the pattern currently used in the existing microservices, which is to check for an env variable and set a default server:port definition if the env variable is not set. Here's an example from `peach-network`:

`let http_server = env::var("PEACH_NETWORK_SERVER").unwrap_or_else(|_| "127.0.0.1:5110".to_string());`

This approach would eliminate the need to incorporate the port definition in the CLI API while also keeping a consistent approach across services.

A list of the microservices and port mappings can be found in the docs: [Configuration](http://docs.peachcloud.org/software/configuration.html).

**Comment by mhfowler** [comment]
Implemented by https://github.com/peachcloud/peach-probe/pull/6
